In [1]:
from synsplore.dataset import SynsploreDataset

dataset = SynsploreDataset(routes_path='../out/routes.pkl', 
                           pharms_path='../out/pharms.pkl')

In [2]:
from torch.utils.data import DataLoader

loader = DataLoader(dataset, collate_fn=lambda x: sum(x), 
                    batch_size=10, shuffle=True)

In [8]:
from synsplore.dataset import RouteData
d: RouteData = next(iter(loader))

In [ ]:
import torch

d.align_right()
o = d.updated_feats_to_transformer_input(
    rfeats=torch.ones(d.rfeats.shape[0], 10),
    pfeats=torch.ones(d.pfeats.shape[0], 10)*2,
    rxnfeats=torch.ones(d.rxnfeats.shape[0], 10)*3,
    startemb=torch.ones(10)*4,
    endemb=torch.ones(10)*5,
    pademb=torch.zeros(10)
)

In [10]:
o[0]

tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [11]:
o.shape

torch.Size([10, 17, 10])

In [8]:
d.ridx

tensor([[ 0, 13],
        [ 1, 13],
        [ 2,  1],
        [ 2,  2],
        [ 2,  8],
        [ 2,  9],
        [ 3, 12],
        [ 3, 13],
        [ 4, 13],
        [ 5, 12],
        [ 5, 13],
        [ 6,  9],
        [ 6, 12],
        [ 7, 12],
        [ 7, 13],
        [ 8, 12],
        [ 8, 13],
        [ 9,  8],
        [ 9,  9],
        [ 9, 12]])

In [5]:
import torch

torch.tensor([1, 2, 3, 3, 3, 4]).unique(return_counts=True)

(tensor([1, 2, 3, 4]), tensor([1, 1, 3, 1]))

In [6]:
torch.arange([1, 2])

TypeError: arange(): argument 'end' (position 1) must be Number, not list

In [23]:
d.pharm_data.typeids

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 0,
        0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 4, 4, 0, 0, 0, 0, 2, 2, 2, 2, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 1, 1, 2, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 0, 0, 0, 1, 1, 2, 3, 3, 3,
        3, 3, 3, 4, 4, 4, 5, 5])

In [24]:
d.pharm_data.values

tensor([ 3.8038,  3.8038,  5.4958,  5.4958,  4.3582,  4.3582,  7.1815,  2.5926,
         2.5926,  1.0317,  1.0317, 10.1247, 10.1247, 12.4216,  3.1648,  3.1648,
         6.5344,  6.5344,  4.4878,  4.4878, 11.9663, 11.9663,  5.7579,  3.2232,
         7.2388,  3.8441,  9.1744, 12.7439,  3.3825,  3.3825,  9.4569,  9.4569,
         3.3825,  3.3825,  9.4569,  9.4569,  3.5456,  3.5456, 11.3820, 11.3820,
         3.5456,  3.5456, 11.3820, 11.3820,  7.3249,  7.3249,  2.5391,  2.5391,
         7.3249,  7.3249,  2.5391,  2.5391,  9.6352,  9.6352,  1.1238,  1.1238,
         4.4143,  6.7846, 10.1520,  4.4143,  6.7846, 10.1520,  2.9415,  8.6098,
        12.2942,  2.9415,  8.6098, 12.2942,  9.9300,  2.8416,  3.0110,  9.9300,
         2.8416,  3.0110, 12.0341,  6.2196,  3.6126,  2.6480,  6.0759, 10.2958,
         2.6480,  6.0759, 10.2958, 11.7028,  5.2890,  2.6432, 11.7028,  5.2890,
         2.6432,  2.3945,  2.3945,  2.3945,  2.3945,  1.1297,  1.1297,  3.5024,
         3.5024,  2.4705,  2.4705, 11.43

In [45]:
l = d.route_data.ridx[:, 1].max()+1
n = d.route_data.ridx[:, 0].max()

In [46]:
l, n

(tensor(7), tensor(9))

In [ ]:
import torch

x = torch.empty(n, l)
x[]

tensor([[ 0.0000e+00,  1.4153e-43,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 4.1196e-02,  4.5744e-41, -3.2158e-25,  ...,  1.2169e-34,
          1.7062e-37,  1.1440e-01],
        [ 4.5744e-41,  1.1440e-01,  4.5744e-41,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 1.4013e-43,  4.2039e-45,  4.2039e-45,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

In [40]:
d.pharm_data.idx[:, 1].max()

tensor(88)

In [41]:
d.pharm_data.idx

tensor([[ 1,  0],
        [ 1,  1],
        [ 1,  2],
        [ 1,  3],
        [ 1,  4],
        [ 1,  5],
        [ 1,  6],
        [ 1,  7],
        [ 1,  8],
        [ 1,  9],
        [ 1, 10],
        [ 1, 11],
        [ 1, 12],
        [ 1, 13],
        [ 1, 14],
        [ 1, 15],
        [ 1, 16],
        [ 1, 17],
        [ 1, 18],
        [ 1, 19],
        [ 1, 20],
        [ 1, 21],
        [ 1, 22],
        [ 1, 23],
        [ 1, 24],
        [ 1, 25],
        [ 1, 26],
        [ 1, 27],
        [ 1, 28],
        [ 1, 29],
        [ 1, 30],
        [ 1, 31],
        [ 1, 32],
        [ 1, 33],
        [ 1, 34],
        [ 1, 35],
        [ 1, 36],
        [ 1, 37],
        [ 1, 38],
        [ 1, 39],
        [ 1, 40],
        [ 1, 41],
        [ 1, 42],
        [ 1, 43],
        [ 1, 44],
        [ 1, 45],
        [ 1, 46],
        [ 1, 47],
        [ 1, 48],
        [ 1, 49],
        [ 1, 50],
        [ 1, 51],
        [ 1, 52],
        [ 1, 53],
        [ 1, 54],
        [ 